export interface MenuItem {
  id: string;
  nameTr: string;
  nameEn: string;
  nameRu: string;
  nameNo: string;
  descriptionTr: string;
  descriptionEn: string;
  descriptionRu: string;
  descriptionNo: string;
  categoryTr: string;
  categoryEn: string;
  categoryRu: string;
  categoryNo: string;
  imageUrl: string | null;
}

export const menuData: MenuItem[] = [
  // --- PIZZALAR / PIZZAS ---
  {
    id: "pizza-34",
    nameTr: "Pizza Margarita",
    nameEn: "Pizza Margherita",
    nameRu: "Пицца Маргарита",
    nameNo: "Pizza Margherita",
    descriptionTr: "Mozzarella peyniri ve domates sos ile hazırlanır.",
    descriptionEn: "Mozzarella cheese and tomato sauce.",
    descriptionRu: "Сыр моцарелла и томатный соус.",
    descriptionNo: "Mozzarella ost og tomatsaus.",
    categoryTr: "Pizzalar",
    categoryEn: "Pizzas",
    categoryRu: "Пицца",
    categoryNo: "Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "pizza-35",
    nameTr: "Mantarlı Pizza (Fungi)",
    nameEn: "Fungi Pizza",
    nameRu: "Грибная пицца (Фунги)",
    nameNo: "Sopp Pizza (Fungi)",
    descriptionTr: "Mozzarella peyniri, kültür mantarı ve domates sos ile hazırlanır.",
    descriptionEn: "Mozzarella cheese, mushrooms, and tomato sauce.",
    descriptionRu: "Сыр моцарелла, шампиньоны и томатный соус.",
    descriptionNo: "Mozzarella ost, sjampinjong og tomatsaus.",
    categoryTr: "Pizzalar",
    categoryEn: "Pizzas",
    categoryRu: "Пицца",
    categoryNo: "Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "pizza-36",
    nameTr: "Karışık Pizza",
    nameEn: "Mixed Pizza",
    nameRu: "Ассорти пицца",
    nameNo: "Miks Pizza",
    descriptionTr: "Sucuk, salam, jambon, mantar, domates, yeşil biber, siyah zeytin ve domates sos ile hazırlanır.",
    descriptionEn: "Turkish sausage, salami, ham, mushrooms, green peppers, black olives, and tomato sauce.",
    descriptionRu: "Турецкая колбаса суджук, салями, ветчина, грибы, зеленый перец, черные маслины и томатный соус.",
    descriptionNo: "Tyrkisk pølse, salami, skinke, sopp, grønn paprika, svarte oliven og tomatsaus.",
    categoryTr: "Pizzalar",
    categoryEn: "Pizzas",
    categoryRu: "Пицца",
    categoryNo: "Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "pizza-37",
    nameTr: "Sucuklu Pizza (Pepperoni)",
    nameEn: "Turkish Pepperoni Pizza",
    nameRu: "Пицца с суджуком (Пепперони)",
    nameNo: "Pølse Pizza (Pepperoni)",
    descriptionTr: "Sucuk ve domates sos ile hazırlanır.",
    descriptionEn: "Turkish sausage and tomato sauce.",
    descriptionRu: "Турецкая колбаса суджук и томатный соус.",
    descriptionNo: "Tyrkisk pølse og tomatsaus.",
    categoryTr: "Pizzalar",
    categoryEn: "Pizzas",
    categoryRu: "Пицца",
    categoryNo: "Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "pizza-38",
    nameTr: "Pizza Bolonez",
    nameEn: "Pizza Bolognese",
    nameRu: "Пицца Болоньезе",
    nameNo: "Pizza Bolognese",
    descriptionTr: "Bolonez sos ve domates sos ile hazırlanır.",
    descriptionEn: "Bolognese sauce and tomato sauce.",
    descriptionRu: "Соус болоньезе и томатный соус.",
    descriptionNo: "Bolognese saus og tomatsaus.",
    categoryTr: "Pizzalar",
    categoryEn: "Pizzas",
    categoryRu: "Пицца",
    categoryNo: "Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "pizza-39",
    nameTr: "Pizza Hawaii",
    nameEn: "Pizza Hawaii",
    nameRu: "Пицца Гавайская",
    nameNo: "Pizza Hawaii",
    descriptionTr: "Salam, jambon, mantar ve ananas ile hazırlanır.",
    descriptionEn: "Salami, ham, mushroom, pineapple.",
    descriptionRu: "Салями, ветчина, грибы и ананас.",
    descriptionNo: "Salami, skinke, sopp og ananas.",
    categoryTr: "Pizzalar",
    categoryEn: "Pizzas",
    categoryRu: "Пицца",
    categoryNo: "Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "pizza-40",
    nameTr: "Vejeteryan Pizza",
    nameEn: "Vegetarian Pizza",
    nameRu: "Вегетарианская пицца",
    nameNo: "Vegetarisk Pizza",
    descriptionTr: "Patlıcan, kabak, biber, sarımsak ve roka ile hazırlanır.",
    descriptionEn: "Grilled eggplant, zucchini, peppers, garlic, and rocket leaves.",
    descriptionRu: "Баклажаны гриль, цукини, перец, чеснок и листья рукколы.",
    descriptionNo: "Grillet aubergine, squash, paprika, hvitløk og ruccola.",
    categoryTr: "Pizzalar",
    categoryEn: "Pizzas",
    categoryRu: "Пицца",
    categoryNo: "Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1573821663912-569905455b1c?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "pizza-41",
    nameTr: "Ton Balıklı Pizza",
    nameEn: "Tonno Pizza",
    nameRu: "Пицца с тунцом",
    nameNo: "Tunfisk Pizza (Tonno)",
    descriptionTr: "Ton balığı, soğan, zeytin, biber ve roka ile hazırlanır.",
    descriptionEn: "Tuna, onion, olives, peppers, and rocket leaves.",
    descriptionRu: "Тунец, лук, оливки, перец и листья рукколы.",
    descriptionNo: "Tunfisk, løk, oliven, paprika og ruccola.",
    categoryTr: "Pizzalar",
    categoryEn: "Pizzas",
    categoryRu: "Пицца",
    categoryNo: "Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "pizza-42",
    nameTr: "Jambonlu Pizza",
    nameEn: "Pizza Ham",
    nameRu: "Пицца с ветчиной",
    nameNo: "Skinke Pizza",
    descriptionTr: "Mozzarella peyniri ve jambon ile hazırlanır.",
    descriptionEn: "Mozzarella cheese and ham.",
    descriptionRu: "Сыр моцарелла и ветчина.",
    descriptionNo: "Mozzarella ost og skinke.",
    categoryTr: "Pizzalar",
    categoryEn: "Pizzas",
    categoryRu: "Пицца",
    categoryNo: "Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1555072956-7758afb20e8f?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "pizza-43",
    nameTr: "Pizza Calzone",
    nameEn: "Pizza Calzone",
    nameRu: "Пицца Кальцоне",
    nameNo: "Pizza Calzone",
    descriptionTr: "Mozzarella, jambon, mantar, karabiber ve domates sos ile hazırlanır.",
    descriptionEn: "Mozzarella cheese, ham, mushrooms, black pepper, and tomato sauce.",
    descriptionRu: "Моцарелла, ветчина, грибы, черный перец и томатный соус.",
    descriptionNo: "Mozzarella, skinke, sopp, svart pepper og tomatsaus.",
    categoryTr: "Pizzalar",
    categoryEn: "Pizzas",
    categoryRu: "Пицца",
    categoryNo: "Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1613564834361-9436948817d1?w=600&auto=format&fit=crop&q=80"
  },

  // --- EV GURME PIZZALAR / GOURMET PIZZAS ---
  {
    id: "gourmet-44",
    nameTr: "Gorgonzola Pizza",
    nameEn: "Gorgonzola Pizza",
    nameRu: "Пицца Горгонзола",
    nameNo: "Gorgonzola Pizza",
    descriptionTr: "Mozzarella ve gorgonzola peyniri ile hazırlanır.",
    descriptionEn: "Mozzarella and gorgonzola cheese.",
    descriptionRu: "Моцарелла и сыр горгонзола.",
    descriptionNo: "Mozzarella og gorgonzola ost.",
    categoryTr: "Gurme Pizzalar",
    categoryEn: "Gourmet Pizzas",
    categoryRu: "Гурме Пицца",
    categoryNo: "Gourmet Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "gourmet-45",
    nameTr: "Dört Peynirli Pizza (Quatro Formagi)",
    nameEn: "Quatro Formaggi Pizza",
    nameRu: "Пицца Четыре сыра (Кватро Формаджи)",
    nameNo: "Fire Oster (Quatro Formagi)",
    descriptionTr: "Mozzarella, parmesan, cheddar, rokfor peyniri ve kremalı krema sos ile hazırlanır.",
    descriptionEn: "Mozzarella, parmesan, cheddar, roquefort cheese, and garlic cream sauce.",
    descriptionRu: "Моцарелла, пармезан, чеддер, сыр рокфор и чесночно-сливочный соус.",
    descriptionNo: "Mozzarella, parmesan, cheddar, roquefort ost og hvitløksfløtesaus.",
    categoryTr: "Gurme Pizzalar",
    categoryEn: "Gourmet Pizzas",
    categoryRu: "Гурме Пицца",
    categoryNo: "Gourmet Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "gourmet-46",
    nameTr: "Rustik Pizza",
    nameEn: "Rustic Pizza",
    nameRu: "Рустик Пицца",
    nameNo: "Rustikk Pizza",
    descriptionTr: "Pesto sos, mozzarella peyniri, körpe roka yaprakları, lor peyniri ve parmesan ile hazırlanır.",
    descriptionEn: "Prepared with pesto sauce, mozzarella cheese, rocket leaves, lor cheese, and parmesan.",
    descriptionRu: "Соус песто, сыр моцарелла, свежие листья рукколы, творожный сыр лор и пармезан.",
    descriptionNo: "Laget med pestosaus, mozzarellaost, ruccolablader, ferskost og parmesan.",
    categoryTr: "Gurme Pizzalar",
    categoryEn: "Gourmet Pizzas",
    categoryRu: "Гурме Пицца",
    categoryNo: "Gourmet Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1576458088443-04a19bb13da6?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "gourmet-47",
    nameTr: "Deniz Mahsülleri Pizza",
    nameEn: "Seafood Pizza",
    nameRu: "Пицца с морепродуктами",
    nameNo: "Sjømat Pizza",
    descriptionTr: "Domates sos, mozzarella peyniri, mantar, kalamar ve karides ile hazırlanır.",
    descriptionEn: "Prepared with tomato sauce, mozzarella cheese, mushrooms, calamari, and shrimps.",
    descriptionRu: "Томатный соус, сыр моцарелла, грибы, кальмары и креветки.",
    descriptionNo: "Laget med tomatsaus, mozzarellaost, sopp, akkar og reker.",
    categoryTr: "Gurme Pizzalar",
    categoryEn: "Gourmet Pizzas",
    categoryRu: "Гурме Пицца",
    categoryNo: "Gourmet Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1576458088443-04a19bb13da6?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "gourmet-48",
    nameTr: "EV'e Özel Pizza",
    nameEn: "EV Special Pizza",
    nameRu: "Фирменная пицца EV",
    nameNo: "EV Spesialpizza",
    descriptionTr: "Fırında pişmiş tiftiklenmiş dana kaburga, mozzarella peyniri, cheddar peyniri, domates sos ve köz biber ile hazırlanır.",
    descriptionEn: "Prepared with shredded beef ribs, mozzarella cheese, cheddar cheese, tomato sauce, and roasted peppers.",
    descriptionRu: "Нежные кусочки запеченных говяжьих ребрышек, сыр моцарелла, сыр чеддер, томатный соус и запеченный перец.",
    descriptionNo: "Laget med strimlet storfekjøttribbe, mozzarellaost, cheddarost, tomatsaus og grillet paprika.",
    categoryTr: "Gurme Pizzalar",
    categoryEn: "Gourmet Pizzas",
    categoryRu: "Гурме Пицца",
    categoryNo: "Gourmet Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "gourmet-49",
    nameTr: "BBQ Tavuk Pizza",
    nameEn: "BBQ Chicken Pizza",
    nameRu: "Барбекю цыпленок пицца",
    nameNo: "BBQ Kylling Pizza",
    descriptionTr: "Mozzarella peyniri, barbekü soslu tavuk, soğan ve jalapeño biberi ile hazırlanır.",
    descriptionEn: "Prepared with mozzarella cheese, BBQ chicken, onions, green peppers, and jalapeños.",
    descriptionRu: "Сыр моцарелла, курица в соусе барбекю, лук, зеленый перец и халапеньо.",
    descriptionNo: "Laget med mozzarellaost, BBQ-kylling, løk, grønn paprika og jalapeños.",
    categoryTr: "Gurme Pizzalar",
    categoryEn: "Gourmet Pizzas",
    categoryRu: "Гурме Пицца",
    categoryNo: "Gourmet Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "gourmet-50",
    nameTr: "Pizza Carpaccio",
    nameEn: "Pizza Carpaccio",
    nameRu: "Пицца Карпаччо",
    nameNo: "Pizza Carpaccio",
    descriptionTr: "Mozzarella, dana carpaccio, körpe roka yaprakları ve parmesan ile hazırlanır.",
    descriptionEn: "Prepared with mozzarella cheese, beef carpaccio, rocket leaves, and parmesan cheese.",
    descriptionRu: "Моцарелла, карпаччо из говядины, свежие листья рукколы и сыр пармезан.",
    descriptionNo: "Laget med mozzarellaost, biff carpaccio, ruccolablader og parmesanost.",
    categoryTr: "Gurme Pizzalar",
    categoryEn: "Gourmet Pizzas",
    categoryRu: "Гурме Пицца",
    categoryNo: "Gourmet Pizzas",
    imageUrl: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&auto=format&fit=crop&q=80"
  },

  // --- TAVUK YEMEKLERİ / CHICKEN DISHES ---
  {
    id: "chicken-51",
    nameTr: "Hint Usulü Tavuk",
    nameEn: "Indian Style Chicken",
    nameRu: "Курица по-индийски",
    nameNo: "Kylling i indisk stil",
    descriptionTr: "Köri sosu, krema, marine edilmiş tavuk, patlıcan, kabak, sarımsak ve zerdeçal ile hazırlanır. Sebzeli kremalı pilav ile servis edilir.",
    descriptionEn: "Marinated chicken cooked with curry sauce, cream, eggplant, zucchini, garlic, and turmeric. Served with creamy vegetable rice.",
    descriptionRu: "Маринованная курица, приготовленная с соусом карри, сливками, баклажанами, цукини, чесноком и куркумой. Подается со сливочно-овощным рисом.",
    descriptionNo: "Marinert kylling tilberedt med karrisaus, fløte, aubergine, squash, hvitløk og gurkemeie. Serveres med kremet grønnsaksris.",
    categoryTr: "Tavuk Yemekleri",
    categoryEn: "Chicken Dishes",
    categoryRu: "Блюда из курицы",
    categoryNo: "Kyllingretter",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "chicken-52",
    nameTr: "Soya Soslu Tavuk",
    nameEn: "Soy Sauce Chicken",
    nameRu: "Курица в соевом соусе",
    nameNo: "Kylling i soyasaus",
    descriptionTr: "Sarımsak, mantar, soya sos ve krema ile hazırlanır. Bebek patates ve mevsim sebzeleri ile servis edilir.",
    descriptionEn: "Marinated chicken cooked with soy sauce, garlic, mushrooms, and cream. Served with baby potatoes and seasonal vegetables.",
    descriptionRu: "Маринованная курица, приготовленная с соевым соусом, чесноком, грибами и сливками. Подается с молодым картофелем и сезонными овощами.",
    descriptionNo: "Marinert kylling tilberedt med soyasaus, hvitløk, sopp og fløte. Serveres med småpoteter og sesongens grønnsaker.",
    categoryTr: "Tavuk Yemekleri",
    categoryEn: "Chicken Dishes",
    categoryRu: "Блюда из курицы",
    categoryNo: "Kyllingretter",
    imageUrl: "https://images.unsplash.com/photo-1598515214211-89d3e73ae83b?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "chicken-53",
    nameTr: "Peynirli Tavuk",
    nameEn: "Chicken Alla Quattro Formaggi",
    nameRu: "Курица Четыре сыра",
    nameNo: "Kylling med fire oster",
    descriptionTr: "Parmesan, rokfor, cheddar, gorgonzola ve krema sos ile hazırlanır. Bebek patates ve sebzeler ile servis edilir.",
    descriptionEn: "Marinated chicken cooked in parmesan, roquefort, cheddar, gorgonzola, and cream sauce. Served with baby potatoes and seasonal vegetables.",
    descriptionRu: "Маринованная курица в соусе из пармезана, рокфора, чеддера, горгонзолы и сливок. Подается с молодым картофелем и сезонными овощами.",
    descriptionNo: "Marinert kylling tilberedt i parmesan, roquefort, cheddar, gorgonzola og fløtesaus. Serveres med småpoteter og sesongens grønnsaker.",
    categoryTr: "Tavuk Yemekleri",
    categoryEn: "Chicken Dishes",
    categoryRu: "Блюда из курицы",
    categoryNo: "Kyllingretter",
    imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "chicken-54",
    nameTr: "EV'e Özel Tavuk Şinitsel",
    nameEn: "Ev Chicken Schnitzel",
    nameRu: "Фирменный куриный шницель EV",
    nameNo: "EV Kyllingsnitzel",
    descriptionTr: "Patates kızartması, mevsim sebzeleri ve Cafe de Paris sos ile servis edilir.",
    descriptionEn: "Served with French fries, seasonal vegetables, and Cafe de Paris sauce.",
    descriptionRu: "Подается с картофелем фри, сезонными овощами и соусом Кафе де Пари.",
    descriptionNo: "Serveres med pommes frites, sesongens grønnsaker og Cafe de Paris-saus.",
    categoryTr: "Tavuk Yemekleri",
    categoryEn: "Chicken Dishes",
    categoryRu: "Блюда из курицы",
    categoryNo: "Kyllingretter",
    imageUrl: "https://images.unsplash.com/photo-1594834749740-74b3f6764be4?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "chicken-55",
    nameTr: "Izgara Tavuk Göğsü",
    nameEn: "Grilled Chicken Supreme",
    nameRu: "Куриная грудка на гриле",
    nameNo: "Grillet kyllingbryst",
    descriptionTr: "Mantar soslu ızgara tavuk göğsü, mevsim sebzeleri ve patates ile servis edilir.",
    descriptionEn: "Grilled chicken breast served with creamy mushroom sauce, potatoes, and seasonal vegetables.",
    descriptionRu: "Куриная грудка на гриле со сливочно-грибным соусом, картофелем и сезонными овощами.",
    descriptionNo: "Grillet kyllingbryst serveres med kremet soppsaus, poteter og sesongens grønnsaker.",
    categoryTr: "Tavuk Yemekleri",
    categoryEn: "Chicken Dishes",
    categoryRu: "Блюда из курицы",
    categoryNo: "Kyllingretter",
    imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "chicken-56",
    nameTr: "Izgara Tavuk Şiş",
    nameEn: "Chicken Shish",
    nameRu: "Куриный шашлык",
    nameNo: "Kyllingspyd (Shish)",
    descriptionTr: "Patates ve ızgara sebzeler ile servis edilir.",
    descriptionEn: "Served with potatoes and grilled vegetables.",
    descriptionRu: "Подается с картофелем и овощами гриль.",
    descriptionNo: "Serveres med poteter og grillede grønnsaker.",
    categoryTr: "Tavuk Yemekleri",
    categoryEn: "Chicken Dishes",
    categoryRu: "Блюда из курицы",
    categoryNo: "Kyllingretter",
    imageUrl: "https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "chicken-57",
    nameTr: "Tatlı ve Ekşi Soslu Ananaslı Tavuk",
    nameEn: "Sweet & Sour Chicken Pineapple",
    nameRu: "Курица с ананасом в кисло-сладком соусе",
    nameNo: "Kylling med ananas i søtsur saus",
    descriptionTr: "Marine edilmiş tavuk parçaları, ananas, biber, bebek mısır ve tatlı ekşi sos ile hazırlanır. Sebzeli kremalı pilav ile servis edilir.",
    descriptionEn: "Marinated chicken pieces cooked with pineapple, peppers, baby corn, and sweet & sour sauce. Served with creamy vegetable rice.",
    descriptionRu: "Кусочки маринованной курицы с ананасом, перцем, молодой кукурузой и кисло-сладким соусом. Подается со сливочно-овощным рисом.",
    descriptionNo: "Marinert kyllingbiter tilberedt med ananas, paprika, minimais og søtsur saus. Serveres med kremet grønnsaksris.",
    categoryTr: "Tavuk Yemekleri",
    categoryEn: "Chicken Dishes",
    categoryRu: "Блюда из курицы",
    categoryNo: "Kyllingretter",
    imageUrl: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "chicken-58",
    nameTr: "Ustanın Özel Sosuyla Tavuk But",
    nameEn: "Chef's Special Sauce Chicken Leg",
    nameRu: "Куриное бедро в фирменном соусе",
    nameNo: "Kyllinglår med kokkens spesialsaus",
    descriptionTr: "Izgara tavuk but, ızgara çeri domates, mevsim sebzeleri, roka, patates ve özel körili mantar sos ile servis edilir.",
    descriptionEn: "Grilled chicken leg served with cherry tomatoes, seasonal vegetables, rocket leaves, potatoes, and special curry mushroom sauce.",
    descriptionRu: "Куриное бедро на гриле, подается с томатами черри, сезонными овощами, рукколой, картофелем и особым грибным соусом карри.",
    descriptionNo: "Grillet kyllinglår serveres med kirsebærtomater, sesongens grønnsaker, ruccola, poteter og en spesiell karrisoppsaus.",
    categoryTr: "Tavuk Yemekleri",
    categoryEn: "Chicken Dishes",
    categoryRu: "Блюда из курицы",
    categoryNo: "Kyllingretter",
    imageUrl: "https://images.unsplash.com/photo-1598515214211-89d3e73ae83b?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "chicken-59",
    nameTr: "Meksika Usulü Tavuk",
    nameEn: "Mexican Style Chicken",
    nameRu: "Курица по-мексикански",
    nameNo: "Kylling i meksikansk stil",
    descriptionTr: "Acı biber, Meksika fasulyesi, bebek mısır ve sarımsak ile hazırlanır. Sebzeli kremalı pilav ve patates ile servis edilir.",
    descriptionEn: "Prepared with hot chili peppers, Mexican beans, baby corn, and garlic. Served with creamy vegetable rice and potatoes.",
    descriptionRu: "Приготовлено с острым перцем чили, мексиканской фасолью, молодой кукурузой и чесноком. Подается со сливочно-овощным рисом и картофелем.",
    descriptionNo: "Tilberedt med sterk chili, meksikanske bønner, minimais og hvitløk. Serveres med kremet grønnsaksris og poteter.",
    categoryTr: "Tavuk Yemekleri",
    categoryEn: "Chicken Dishes",
    categoryRu: "Блюда из курицы",
    categoryNo: "Kyllingretter",
    imageUrl: "https://images.unsplash.com/photo-1565299543923-37dd37887442?w=600&auto=format&fit=crop&q=80"
  },

  // --- TÜRK MUTFAĞI / TURKISH KITCHEN ---
  {
    id: "turkish-60",
    nameTr: "Kuzu İncik Marmarina",
    nameEn: "Lamb Shank Marmarina",
    nameRu: "Голяшка ягненка Мармарина",
    nameNo: "Lammeskank Marmarina",
    descriptionTr: "Çeşitli baharatlarla 6 saat pişirilmiş kuzu incik, patates püresi ve brokoli ile servis edilir.",
    descriptionEn: "Slow-cooked lamb shank prepared with Ottoman spices, served with mashed potatoes and broccoli.",
    descriptionRu: "Томленая голяшка ягненка, приготовленная с османскими специями, подается с картофельным пюре и брокколи.",
    descriptionNo: "Langtidskokt lammeskank tilberedt med osmanske krydder, serveres med potetmos og brokkoli.",
    categoryTr: "Türk Mutfağı",
    categoryEn: "Turkish Kitchen",
    categoryRu: "Турецкая кухня",
    categoryNo: "Tyrkisk kjøkken",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "turkish-61",
    nameTr: "Dana Şiş Kebap",
    nameEn: "Beef Kebab",
    nameRu: "Шиш-кебаб из говядины",
    nameNo: "Biff Kebabspyd",
    descriptionTr: "Fırında bebek patates ve ızgara sebzeler ile servis edilir.",
    descriptionEn: "Served with baby potatoes and grilled vegetables.",
    descriptionRu: "Подается с молодым картофелем в духовке и овощами гриль.",
    descriptionNo: "Serveres med ovnsbakte småpoteter og grillede grønnsaker.",
    categoryTr: "Türk Mutfağı",
    categoryEn: "Turkish Kitchen",
    categoryRu: "Турецкая кухня",
    categoryNo: "Tyrkisk kjøkken",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "turkish-62",
    nameTr: "Et Sote (Osmanish)",
    nameEn: "Osmanish Beef Sauté",
    nameRu: "Мясное соте по-османски",
    nameNo: "Meksikansk/Osmansk Biffgryte",
    descriptionTr: "Dana eti, domates, yeşil biber, soğan, sarımsak ve mantar ile hazırlanır. Sebzeli pilav ile servis edilir.",
    descriptionEn: "Beef sautéed with tomatoes, green peppers, onions, garlic, and mushrooms. Served with vegetable rice.",
    descriptionRu: "Говядина, обжаренная с помидорами, зеленым перцем, луком, чесноком и грибами. Подается с рисом с овощами.",
    descriptionNo: "Biff stekt med tomater, grønn paprika, løk, hvitløk og sopp. Serveres med grønnsaksris.",
    categoryTr: "Türk Mutfağı",
    categoryEn: "Turkish Kitchen",
    categoryRu: "Турецкая кухня",
    categoryNo: "Tyrkisk kjøkken",
    imageUrl: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "turkish-63",
    nameTr: "Karışık Izgara",
    nameEn: "Mixed Grill",
    nameRu: "Гриль-ассорти",
    nameNo: "Grilltallerken (Mixed Grill)",
    descriptionTr: "Kuzu pirzola, et şiş, tavuk şiş ve köfte; fırında bebek patates ve ızgara sebzeler ile servis edilir.",
    descriptionEn: "Lamb chops, beef skewers, chicken skewers, and meatballs served with baby potatoes and grilled vegetables.",
    descriptionRu: "Отбивные из ягненка, шашлык из говядины, куриный шашлык и фрикадельки-кёфте. Подается с молодым картофелем и овощами гриль.",
    descriptionNo: "Lammekoteletter, biffspyd, kyllingspyd og kjøttboller serveres med småpoteter og grillede grønnsaker.",
    categoryTr: "Türk Mutfağı",
    categoryEn: "Turkish Kitchen",
    categoryRu: "Турецкая кухня",
    categoryNo: "Tyrkisk kjøkken",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "turkish-64",
    nameTr: "Izgara Köfte",
    nameEn: "Grilled Meatballs",
    nameRu: "Кёфте на гриле",
    nameNo: "Grillede Kjøttboller (Köfte)",
    descriptionTr: "Pide yatağında ızgara köfte, sarımsaklı yoğurtlu patlıcan, bebek patates ve ızgara sebzeler ile servis edilir.",
    descriptionEn: "Grilled meatballs served on pita bread with garlic yogurt eggplant, baby potatoes, and grilled vegetables.",
    descriptionRu: "Кёфте на гриле подаются на лаваше с баклажанами в чесночном йогурте, молодым картофелем и овощами гриль.",
    descriptionNo: "Grillede tyrkiske kjøttboller servert på pitabrød med hvitløksyoghurt-aubergine, småpoteter og grillede grønnsaker.",
    categoryTr: "Türk Mutfağı",
    categoryEn: "Turkish Kitchen",
    categoryRu: "Турецкая кухня",
    categoryNo: "Tyrkisk kjøkken",
    imageUrl: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "turkish-65",
    nameTr: "Alinazik",
    nameEn: "Alinazik Kebab",
    nameRu: "Али Назик Кебаб",
    nameNo: "Alinazik Biff",
    descriptionTr: "Dana bonfile, yoğurtlu köz patlıcan ve toz biberli tereyağı ile servis edilir.",
    descriptionEn: "Beef tenderloin served with smoked eggplant puree, yogurt, and chili butter.",
    descriptionRu: "Нежная говяжья вырезка, подается с пюре из копченых баклажанов с йогуртом и сливочным маслом с красным перцем.",
    descriptionNo: "Biff indrefilet serveres med røkt auberginepure, yoghurt og chilismør.",
    categoryTr: "Türk Mutfağı",
    categoryEn: "Turkish Kitchen",
    categoryRu: "Турецкая кухня",
    categoryNo: "Tyrkisk kjøkken",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "turkish-66",
    nameTr: "Patlıcan Yatağında Tavuk",
    nameEn: "Chicken on Smoked Eggplant",
    nameRu: "Курица на баклажанном пюре",
    nameNo: "Kylling på aubergineseng",
    descriptionTr: "Izgara tavuk, yoğurtlu köz patlıcan salatası üzerinde servis edilir.",
    descriptionEn: "Grilled chicken served on smoked eggplant puree with yogurt.",
    descriptionRu: "Курица на гриле, подается на салате из запеченных баклажанов с йогуртом.",
    descriptionNo: "Grillet kylling servert på røkt auberginesalat med yoghurt.",
    categoryTr: "Türk Mutfağı",
    categoryEn: "Turkish Kitchen",
    categoryRu: "Турецкая кухня",
    categoryNo: "Tyrkisk kjøkken",
    imageUrl: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "turkish-67",
    nameTr: "Sultanlara Özel Ballı Tavuk",
    nameEn: "Ottoman Style Honey Chicken",
    nameRu: "Курица с медом по-османски",
    nameNo: "Ottoman Stil Honningkylling",
    descriptionTr: "Marine edilmiş tavuk; soğan, bal, çiğ badem, kuru üzüm, maydanoz, tarçın, tereyağı ve limon ile hazırlanır. Pilav ile servis edilir.",
    descriptionEn: "Marinated chicken cooked with onions, honey, almonds, raisins, black pepper, parsley, cinnamon, butter, and lemon. Served with rice.",
    descriptionRu: "Маринованная курица, приготовленная с луком, медом, миндалем, изюмом, черным перцем, петрушкой, корицей, сливочным маслом и лимоном. Подается с рисом.",
    descriptionNo: "Marinert kylling tilberedt med løk, honning, mandler, rosiner, svart pepper, persille, kanel, smør og sitron. Serveres med ris.",
    categoryTr: "Türk Mutfağı",
    categoryEn: "Turkish Kitchen",
    categoryRu: "Турецкая кухня",
    categoryNo: "Tyrkisk kjøkken",
    imageUrl: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "turkish-68",
    nameTr: "Sosyete Kebap",
    nameEn: "Pistachio Kebab on Smoky Eggplant",
    nameRu: "Сосьете Кебаб",
    nameNo: "Pistasj-Kebab på røkt aubergine",
    descriptionTr: "EV'e özel Antep fıstıklı peynirli kebap, peynirli patlıcan söğürme, ızgara biber ve tereyağlı pide ile servis edilir.",
    descriptionEn: "Special pistachio cheese kebab served with smoked eggplant, grilled peppers, and buttered pita bread.",
    descriptionRu: "Фирменный кебаб с фисташками и сыром, подается с запеченными баклажанами с сыром, обжаренным перцем и лепешкой с маслом.",
    descriptionNo: "Spesiell pistasj-ostekebab serveres med røkt aubergine, grillet paprika og smurt pitabrød.",
    categoryTr: "Türk Mutfağı",
    categoryEn: "Turkish Kitchen",
    categoryRu: "Турецкая кухня",
    categoryNo: "Tyrkisk kjøkken",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "turkish-69",
    nameTr: "Izgara Kuzu Pirzola",
    nameEn: "Grilled Lamb Chops",
    nameRu: "Отбивные из ягненка на гриле",
    nameNo: "Grillede Lammekoteletter",
    descriptionTr: "Bebek patates ve ızgara sebzeler ile servis edilir.",
    descriptionEn: "Served with baby potatoes and grilled vegetables.",
    descriptionRu: "Подается с молодым картофелем и овощами гриль.",
    descriptionNo: "Serveres med småpoteter og grillede grønnsaker.",
    categoryTr: "Türk Mutfağı",
    categoryEn: "Turkish Kitchen",
    categoryRu: "Турецкая кухня",
    categoryNo: "Tyrkisk kjøkken",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80"
  },

  // --- IZGARA ÇEŞİTLERİ / GRILL & ROAST ---
  {
    id: "grill-70",
    nameTr: "Ev Special Fillet Steak",
    nameEn: "Ev Special Fillet Steak",
    nameRu: "Фирменный филе-стейк EV",
    nameNo: "EV Spesial Ytrefilet",
    descriptionTr: "Üç farklı sos, fırında bebek patates ve mevsim sebzeleri ile servis edilir.",
    descriptionEn: "Served with mushroom, béarnaise, and pepper sauce, alongside baby potatoes and seasonal vegetables.",
    descriptionRu: "Подается с тремя соусами, молодым запеченным картофелем и сезонными овощами.",
    descriptionNo: "Serveres med sopp-, béarnaise- og peppersaus, samt småpoteter og sesongens grønnsaker.",
    categoryTr: "Izgara Çeşitleri",
    categoryEn: "Grill & Roast",
    categoryRu: "Гриль и жаркое",
    categoryNo: "Grillretter",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "grill-71",
    nameTr: "Plank Fillet Steak",
    nameEn: "Plank Fillet Steak",
    nameRu: "Планк стейк из филе",
    nameNo: "Plankebiff",
    descriptionTr: "Özel mantar sos, patates püresi ve mevsim sebzeleri ile servis edilir.",
    descriptionEn: "Fillet steak served with mashed potatoes and seasonal vegetables.",
    descriptionRu: "Стейк из филе, подается с картофельным пюре и сезонными овощами с грибным соусом.",
    descriptionNo: "Indrefilet serveres med potetmos og sesongens grønnsaker med soppsaus.",
    categoryTr: "Izgara Çeşitleri",
    categoryEn: "Grill & Roast",
    categoryRu: "Гриль и жаркое",
    categoryNo: "Grillretter",
    imageUrl: "https://images.unsplash.com/photo-1546964124-0cce460f38ef?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "grill-72",
    nameTr: "Café de Paris Ribeye Steak",
    nameEn: "Café de Paris Ribeye Steak",
    nameRu: "Рибай-стейк Кафе де Пари",
    nameNo: "Café de Paris Entrecôte",
    descriptionTr: "Cafe de Paris sosu, fırında bebek patates ve mevsim sebzeleri ile servis edilir.",
    descriptionEn: "Entrecôte steak served with Café de Paris sauces, baby potatoes, and seasonal vegetables.",
    descriptionRu: "Стейк рибай, подается с соусом Кафе де Пари, запеченным картофелем и сезонными овощами.",
    descriptionNo: "Entrecôte serveres med Café de Paris-saus, småpoteter og sesongens grønnsaker.",
    categoryTr: "Izgara Çeşitleri",
    categoryEn: "Grill & Roast",
    categoryRu: "Гриль и жаркое",
    categoryNo: "Grillretter",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "grill-73",
    nameTr: "Onion & Wine Ribeye Steak",
    nameEn: "Onion & Wine Ribeye Steak",
    nameRu: "Рибай-стейк с луком и вином",
    nameNo: "Løk & Vin Entrecôte",
    descriptionTr: "Fırında patates, mevsim sebzeleri ve kırmızı şarapla tatlandırılmış karamelize soğan ile servis edilir.",
    descriptionEn: "Served with potatoes, seasonal vegetables, and caramelized onions flavored with red wine.",
    descriptionRu: "Подается с запеченным картофелем, сезонными овощами и карамелизованным луком, приправленным красным вином.",
    descriptionNo: "Serveres med poteter, sesongens grønnsaker og karamellisert løk smaksatt med rødvin.",
    categoryTr: "Izgara Çeşitleri",
    categoryEn: "Grill & Roast",
    categoryRu: "Гриль и жаркое",
    categoryNo: "Grillretter",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "grill-74",
    nameTr: "Dana Lokum",
    nameEn: "Beef Tenderloin Lokum",
    nameRu: "Дана Локум (кусочки вырезки)",
    nameNo: "Dana Lokum (Indrefilet biter)",
    descriptionTr: "Kremalı parmesanlı mantar sos, roka ve bebek patates ile servis edilir.",
    descriptionEn: "Served with creamy parmesan mushroom sauce, rocket leaves, and baby potatoes.",
    descriptionRu: "Подается с нежным грибным соусом с пармезаном, рукколой и молодым картофелем.",
    descriptionNo: "Serveres med kremet soppsaus med parmesan, ruccola og småpoteter.",
    categoryTr: "Izgara Çeşitleri",
    categoryEn: "Grill & Roast",
    categoryRu: "Гриль и жаркое",
    categoryNo: "Grillretter",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "grill-75",
    nameTr: "Dana Kaburga",
    nameEn: "Roasted Beef Ribs",
    nameRu: "Говяжьи ребрышки",
    nameNo: "Okseribbe",
    descriptionTr: "Tiftiklenmiş dana kaburga, patates püresi, demi-glace sos ve mevsim sebzeleri ile servis edilir.",
    descriptionEn: "Shredded beef ribs served with mashed potatoes, demi-glace sauce, and seasonal vegetables.",
    descriptionRu: "Сочные томленые говяжьи ребрышки с картофельным пюре, соусом демиглас и сезонными овощами.",
    descriptionNo: "Mørt storfekjøttribbe serveres med potetmos, demiglace-saus og sesongens grønnsaker.",
    categoryTr: "Izgara Çeşitleri",
    categoryEn: "Grill & Roast",
    categoryRu: "Гриль и жаркое",
    categoryNo: "Grillretter",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "grill-76",
    nameTr: "Şefin İmzası",
    nameEn: "Chef's Signature Beef",
    nameRu: "Шеф-сигнейче биф",
    nameNo: "Kokkens Signaturbiff",
    descriptionTr: "Bonfile parçaları, karamelize soğan, istiridye mantarı, kırmızı şarap, demi-glace sos ve krema ile hazırlanır. Pilav ile servis edilir.",
    descriptionEn: "Tenderloin pieces cooked with caramelized onions, oyster mushrooms, garlic, red wine, demi-glace sauce, and cream. Served with rice.",
    descriptionRu: "Кусочки вырезки, приготовленные с карамелизованным луком, вешенками, чесноком, красным вином, соусом демиглас и сливками. Подается с рисом.",
    descriptionNo: "Biffbiter tilberedt med karamellisert løk, østerssopp, hvitløk, rødvin, demiglace-saus og fløte. Serveres med ris.",
    categoryTr: "Izgara Çeşitleri",
    categoryEn: "Grill & Roast",
    categoryRu: "Гриль и жаркое",
    categoryNo: "Grillretter",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80"
  }
];
